// Generated by gencpp from file meam520_labs/BlockDetection.msg
// DO NOT EDIT!


#ifndef MEAM520_LABS_MESSAGE_BLOCKDETECTION_H
#define MEAM520_LABS_MESSAGE_BLOCKDETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace meam520_labs
{
template <class ContainerAllocator>
struct BlockDetection_
{
  typedef BlockDetection_<ContainerAllocator> Type;

  BlockDetection_()
    : id(0)
    , dynamic(false)
    , pose()  {
    }
  BlockDetection_(const ContainerAllocator& _alloc)
    : id(0)
    , dynamic(false)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef int16_t _id_type;
  _id_type id;

   typedef uint8_t _dynamic_type;
  _dynamic_type dynamic;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::meam520_labs::BlockDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::meam520_labs::BlockDetection_<ContainerAllocator> const> ConstPtr;

}; // struct BlockDetection_

typedef ::meam520_labs::BlockDetection_<std::allocator<void> > BlockDetection;

typedef boost::shared_ptr< ::meam520_labs::BlockDetection > BlockDetectionPtr;
typedef boost::shared_ptr< ::meam520_labs::BlockDetection const> BlockDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::meam520_labs::BlockDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::meam520_labs::BlockDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::meam520_labs::BlockDetection_<ContainerAllocator1> & lhs, const ::meam520_labs::BlockDetection_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.dynamic == rhs.dynamic &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::meam520_labs::BlockDetection_<ContainerAllocator1> & lhs, const ::meam520_labs::BlockDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace meam520_labs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::meam520_labs::BlockDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::meam520_labs::BlockDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::meam520_labs::BlockDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::meam520_labs::BlockDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::meam520_labs::BlockDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::meam520_labs::BlockDetection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::meam520_labs::BlockDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f957e4d90fd792d07896c4a471a2f7ef";
  }

  static const char* value(const ::meam520_labs::BlockDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf957e4d90fd792d0ULL;
  static const uint64_t static_value2 = 0x7896c4a471a2f7efULL;
};

template<class ContainerAllocator>
struct DataType< ::meam520_labs::BlockDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "meam520_labs/BlockDetection";
  }

  static const char* value(const ::meam520_labs::BlockDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::meam520_labs::BlockDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 id\n"
"bool dynamic\n"
"geometry_msgs/PoseStamped pose\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::meam520_labs::BlockDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::meam520_labs::BlockDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.dynamic);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BlockDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::meam520_labs::BlockDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::meam520_labs::BlockDetection_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.id);
    s << indent << "dynamic: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dynamic);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MEAM520_LABS_MESSAGE_BLOCKDETECTION_H
