// Generated by gencpp from file meam520_labs/BlockDetectionArray.msg
// DO NOT EDIT!


#ifndef MEAM520_LABS_MESSAGE_BLOCKDETECTIONARRAY_H
#define MEAM520_LABS_MESSAGE_BLOCKDETECTIONARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <meam520_labs/BlockDetection.h>

namespace meam520_labs
{
template <class ContainerAllocator>
struct BlockDetectionArray_
{
  typedef BlockDetectionArray_<ContainerAllocator> Type;

  BlockDetectionArray_()
    : detections()  {
    }
  BlockDetectionArray_(const ContainerAllocator& _alloc)
    : detections(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::meam520_labs::BlockDetection_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::meam520_labs::BlockDetection_<ContainerAllocator> >> _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::meam520_labs::BlockDetectionArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::meam520_labs::BlockDetectionArray_<ContainerAllocator> const> ConstPtr;

}; // struct BlockDetectionArray_

typedef ::meam520_labs::BlockDetectionArray_<std::allocator<void> > BlockDetectionArray;

typedef boost::shared_ptr< ::meam520_labs::BlockDetectionArray > BlockDetectionArrayPtr;
typedef boost::shared_ptr< ::meam520_labs::BlockDetectionArray const> BlockDetectionArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::meam520_labs::BlockDetectionArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::meam520_labs::BlockDetectionArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::meam520_labs::BlockDetectionArray_<ContainerAllocator1> & lhs, const ::meam520_labs::BlockDetectionArray_<ContainerAllocator2> & rhs)
{
  return lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::meam520_labs::BlockDetectionArray_<ContainerAllocator1> & lhs, const ::meam520_labs::BlockDetectionArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace meam520_labs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::meam520_labs::BlockDetectionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::meam520_labs::BlockDetectionArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::meam520_labs::BlockDetectionArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::meam520_labs::BlockDetectionArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::meam520_labs::BlockDetectionArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::meam520_labs::BlockDetectionArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::meam520_labs::BlockDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "40ad97a01f6e1730f483090b7d388a34";
  }

  static const char* value(const ::meam520_labs::BlockDetectionArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x40ad97a01f6e1730ULL;
  static const uint64_t static_value2 = 0xf483090b7d388a34ULL;
};

template<class ContainerAllocator>
struct DataType< ::meam520_labs::BlockDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "meam520_labs/BlockDetectionArray";
  }

  static const char* value(const ::meam520_labs::BlockDetectionArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::meam520_labs::BlockDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "BlockDetection[] detections\n"
"\n"
"================================================================================\n"
"MSG: meam520_labs/BlockDetection\n"
"int16 id\n"
"bool dynamic\n"
"geometry_msgs/PoseStamped pose\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::meam520_labs::BlockDetectionArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::meam520_labs::BlockDetectionArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BlockDetectionArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::meam520_labs::BlockDetectionArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::meam520_labs::BlockDetectionArray_<ContainerAllocator>& v)
  {
    s << indent << "detections[]" << std::endl;
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      s << indent << "  detections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::meam520_labs::BlockDetection_<ContainerAllocator> >::stream(s, indent + "    ", v.detections[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MEAM520_LABS_MESSAGE_BLOCKDETECTIONARRAY_H
