set(_CATKIN_CURRENT_PACKAGE "meam520_labs")
set(meam520_labs_VERSION "0.0.0")
set(meam520_labs_MAINTAINER "Jake Welde <jwelde@seas.upenn.edu>, Shane Rozen-Levy <srozen01@seas.upenn.edu>, Victoria Edwards <vmedw@seas.upenn.edu>, Xu Liu <liuxiu@seas.upenn.edu>")
set(meam520_labs_PACKAGE_FORMAT "1")
set(meam520_labs_BUILD_DEPENDS "message_generation" "geometry_msgs" "std_msgs")
set(meam520_labs_BUILD_EXPORT_DEPENDS "message_runtime" "geometry_msgs" "std_msgs")
set(meam520_labs_BUILDTOOL_DEPENDS "catkin")
set(meam520_labs_BUILDTOOL_EXPORT_DEPENDS )
set(meam520_labs_EXEC_DEPENDS "message_runtime" "geometry_msgs" "std_msgs")
set(meam520_labs_RUN_DEPENDS "message_runtime" "geometry_msgs" "std_msgs")
set(meam520_labs_TEST_DEPENDS )
set(meam520_labs_DOC_DEPENDS )
set(meam520_labs_URL_WEBSITE "")
set(meam520_labs_URL_BUGTRACKER "")
set(meam520_labs_URL_REPOSITORY "")
set(meam520_labs_DEPRECATED "")